# Generated by Django 4.2.4 on 2023-08-24 06:05

import common.utils
import common.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=common.utils.get_default_avatar_path,
                upload_to=common.utils.get_avatar_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Username already taken"},
                help_text="",
                max_length=30,
                unique=True,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                    django.core.validators.MinLengthValidator(
                        limit_value=5,
                        message="Username must have at least 5 characters",
                    ),
                    common.validators.username_validator,
                ],
                verbose_name="Username",
            ),
        ),
    ]
