# Generated by Django 4.2.4 on 2023-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username_last_changed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Username Last Changed on"
            ),
        ),
    ]
