# Generated by Django 4.2.4 on 2023-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_username_last_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deactivated_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deactivated On"
            ),
        ),
    ]
