# Generated by Django 4.2.1 on 2023-05-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(verbose_name="Post Slug"),
        ),
    ]
