# Generated by Django 4.2.1 on 2023-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="unlocked_by",
            new_name="last_unlocked_by",
        ),
        migrations.AlterField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Comment edited at"
            ),
        ),
    ]
