# Generated by Django 4.2.1 on 2023-05-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_rename_unlocked_by_comment_last_unlocked_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="locked_at",
            new_name="last_locked_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="locked_by",
            new_name="last_locked_by",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="unlocked_at",
            new_name="last_unlocked_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="locked_at",
            new_name="last_locked_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="unlocked_at",
            new_name="last_unlocked_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="post.comment",
            ),
        ),
    ]
