# Generated by Django 4.2.4 on 2023-09-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_rename_locked_at_comment_last_locked_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
