# Generated by Django 4.2.4 on 2023-09-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_comment_text_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=250, unique=True, verbose_name="Post Slug"
            ),
        ),
    ]
