# Generated by Django 4.2.1 on 2023-05-08 04:58

import ckeditor.fields
import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_moderators",
                        to="subreddit.moderator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderators",
            },
        ),
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=24, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("about", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "nsfw",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is the Subreddit for NSFW Posts only?",
                    ),
                ),
                ("max_pinned_posts", models.PositiveSmallIntegerField(default=3)),
                ("max_pinned_comments", models.PositiveSmallIntegerField(default=2)),
                (
                    "comments_locked_by_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="Are Post comments locked by default?",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=common.utils.get_default_subreddit_image_path,
                        upload_to=common.utils.get_subreddit_image_path,
                    ),
                ),
                (
                    "cover_picture",
                    models.ImageField(
                        default=common.utils.get_default_subreddit_cover_path,
                        upload_to=common.utils.get_subreddit_cover_path,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        through="subreddit.Moderator", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_subreddits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subreddit",
                "verbose_name_plural": "Subreddits",
            },
        ),
        migrations.CreateModel(
            name="SubredditUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_users",
                        to="subreddit.subreddit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joined_subreddits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subreddit User",
                "verbose_name_plural": "Subreddit Users",
            },
        ),
        migrations.CreateModel(
            name="SubredditLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("url", models.URLField()),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="subreddit.subreddit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subreddit Link",
                "verbose_name_plural": "Subreddit Links",
            },
        ),
        migrations.AddField(
            model_name="moderator",
            name="subreddit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subreddit.subreddit"
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderating_subreddits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
