# Generated by Django 4.2.1 on 2023-05-08 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subreddit", "0002_rename_subredditusers_subreddituser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moderator",
            unique_together={("user", "subreddit")},
        ),
    ]
