# Generated by Django 4.2.1 on 2023-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subreddit", "0005_remove_subreddit_moderators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subredditlink",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterUniqueTogether(
            name="subredditlink",
            unique_together={("subreddit", "name")},
        ),
    ]
